export const commands = [
    "!shuffle",
    "!quality",
    "!boost",
    "!volume",
    "!pause",
    "!play",
    "!stop",
    "!quote",
    "!quoteloop",
    "!quoteall",
    "!troll",
    "!leave",
    "!queue",
    "!viewqueue",
    "!viewplaying",
    "!queuenext",
    "!clearqueue"
]
